(ns flare.configuration)

(defonce default-solr-params
  {:wt "json"
   :fl ["id"
        "score"
        "availability_facet"
        "holdings_with_no_items_display"
        "call_number_display"
        "creator_display"
        "contributor_display"
        "electronic_resource_display"
        "format"
        "imprint_display"
        "library_facet"
        "location_display"
        "pub_date"
        "title_series_display"
        "title_statement_display"
        "title_uniform_display"
        "isbn_display"
        "lccn_display"
        "url_finding_aid_display"
        "bound_with_ids"]
   :defType "edismax"
   :echoParams "explicit"
   :rows "10"
   :mm [ "5<-1" (js/encodeURI "8<75%")]
   :mm.autorelax true
   :lowercaseOperators false
   :ps "3"
   :tie "0.01"
   :qf ["title_unstem_search^100000"
        "subtitle_unstem_search^50000"
        "title_t^25000"
        "subtitle_t^10000"
        "title_statement_unstem_search^15000"
        "title_statement_t^5000"
        "title_uniform_unstem_search^5000"
        "title_uniform_t^2500"
        "title_addl_unstem_search^5000"
        "title_addl_t^2500"
        "title_added_entry_unstem_search^1500"
        "title_added_entry_t^1250"
        "subject_topic_unstem_search^1000"
        "subject_unstem_search^750"
        "subject_topic_facet^625"
        "subject_t^500"
        "creator_unstem_search^250"
        "creator_t^100"
        "subject_addl_unstem_search^250"
        "subject_addl_t^50"
        "title_series_unstem_search^25"
        "title_series_t^10"
        "isbn_t"
        "text"]
   :pf ["title_unstem_search^1000000"
        "subtitle_unstem_search^500000"
        "title_t^250000"
        "subtitle_t^100000"
        "title_statement_unstem_search^150000"
        "title_statement_t^50000"
        "title_uniform_unstem_search^75000"
        "title_uniform_t^50000"
        "title_addl_unstem_search^50000"
        "title_addl_t^25000"
        "title_added_entry_unstem_search^15000"
        "title_added_entry_t^12500"
        "subject_topic_unstem_search^10000"
        "subject_unstem_search^7500"
        "subject_topic_facet^6250"
        "subject_t^5000"
        "note_toc_unstem_search~0^6000"
        "note_summary_unstem_search~0^6000"
        "note_toc_unstem_search^1000"
        "note_summary_unstem_search^1000"
        "creator_unstem_search~2^7500"
        "creator_unstem_search^2500"
        "creator_t^1000"
        "subject_addl_unstem_search^2500"
        "subject_addl_t^500"
        "title_series_unstem_search^250"
        "title_series_t^100"
        "text^10"]
   :author_qf ["creator_unstem_search^200"
               "creator_t^20"]
   :author_pf ["creator_unstem_search^2000"
               "creator_t^200"]
   :title_qf ["title_unstem_search^50000"
              "subtitle_unstem_search^25000"
              "title_uniform_unstem_search^15000"
              "title_addl_unstem_search^10000"
              "title_t^5000"
              "subtitle_t^2500"
              "title_uniform_t^150"
              "title_addl_t^100"
              "title_added_entry_unstem_search^50"
              "title_added_entry_t^10"
              "title_series_unstem_search^5"
              "title_series_t"]
   :title_pf ["title_unstem_search^500000"
              "subtitle_unstem_search^250000"
              "title_uniform_unstem_search^150000"
              "title_addl_unstem_search^100000"
              "title_t^50000"
              "subtitle_t^25000"
              "title_uniform_t^1500"
              "title_addl_t^1000"
              "title_added_entry_unstem_search^500"
              "title_added_entry_t^100"
              "title_series_t^50"
              "title_series_unstem_search^10"]
   :subject_qf ["subject_topic_unstem_search^200"
                "subject_unstem_search^125"
                "subject_topic_facet^100"
                "subject_t^50"
                "subject_addl_unstem_search^10"
                "subject_addl_t"]
   :subject_pf ["subject_topic_unstem_search^2000"
                "subject_unstem_search^1250"
                "subject_t^1000"
                "subject_topic_facet^500"
                "subject_addl_unstem_search^100"
                "subject_addl_t^10"]
   :facet true
   :spellcheck false
   :sow false
   :bq ["pub_date_tdt:[NOW/DAY-10YEAR TO NOW/DAY]^3500"
        "(library_based_boost_t:* -no_boost)^500"]})
